version: '3.8'

services:
  laravel:
    build:
      context: ./laravel-app
      dockerfile: ../Dockerfile
    container_name: laravel
    volumes:
      - ./laravel-app:/var/www/html
    ports:
      - "8000:80"
    networks:
      - entorno-web
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.28
    container_name: bbdd
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - entorno-web
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    networks:
      - entorno-web

networks:
  entorno-web:

volumes:
  mysql_data:
